version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://lambda-builds-zip/m3c1-assignment-lambda
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name m3-c1-assignment-mock-data-lambda --s3-bucket lambda-builds-zip --s3-key m3c1-assignment-lambda/deployment_package.zip
      - echo "Deployment complete!"